apiVersion: apps/v1
kind: Deployment
metadata:
 name: client-deployment
 component: web
spec:
 replicas: 1
 selector: 
  matchLabels:
   component: web
 template:
  metadata:
   labels:
    component: web
  spec:
   containers:
    - name: client
      image: apurwar15/expressapp
      ports:
       - contianerPort : 5000