apiVersion: apps/v1
kind: Deployment
metadata: 
 name: server-deployment
spec: 
 replicas: 3
 selector:
  matchLabels:
   component: server
 template:
  medidata: 
   labels:
    component: server
  spec:
   containers: 
    - name: server
      image: stephengrider/multi-server
      ports:
       - contianerPort : 5000
      env:
       - name: REDIS_HOST
         value: redis-clusterip
       - name: REDIS_PORT
         value: 6379
       - name: PGUSER
         value: postgres
       - name: PGHOST
         value: postgres-clusterip
       - name: PGPORT
         value: 5432
       - name: PGDATABASE
         value: postgres